
    //------------------------------------------------------------------------------
    // <auto-generated>
    //    This code was generated from a template.
    //
    //    Manual changes to this file may cause unexpected behavior in your application.
    //    Manual changes to this file will be overwritten if the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace ShowRoomManagementCenter
    {
        using System;
        using System.Collections.Generic;

        public partial class SearchObject
        {
            public string CNIC { get; set; }
            public string Name { get; set; }
            public string FatherName { get; set; }
            public string Address { get; set; }
            public string PhoneNumber { get; set; }

            public Nullable<System.DateTime> CreationDate { get; set; }

            
            public System.DateTime TransactionDate { get; set; }
            public string GuarantorCNIC { get; set; }
            public decimal Price { get; set; }
            public decimal AdvanceAmount { get; set; }


            public string EngineNumber { get; set; }
            public string ChasisNumber { get; set; }
            public string Model { get; set; }
            public string CC { get; set; }
        
        }
    }

