//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_InstallmentDetail
    {
        public int TransactionId { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string BuyerCNIC { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Remarks { get; set; }
        public string GuarantorCNIC { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public int InstallmentID { get; set; }
        public int InstallmentNumber { get; set; }
        public decimal InstallmentAmount { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> DueDateStart { get; set; }
        public Nullable<System.DateTime> DueDateEnd { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PayedAmount { get; set; }
        public Nullable<bool> Late { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<decimal> TotalAmountPayed { get; set; }
        public Nullable<decimal> TotalAmountRemaining { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int InstaTransactionID { get; set; }
        public Nullable<bool> IsPayed { get; set; }
        public int Id { get; set; }
        public string EngineNumber { get; set; }
        public string ChasisNumber { get; set; }
        public string Model { get; set; }
        public string CC { get; set; }
        public string vRemarks { get; set; }
        public Nullable<System.DateTime> vCreationDate { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<bool> IsOld { get; set; }
        public string CNIC { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneNumber2 { get; set; }
        public string CreditRating { get; set; }
        public Nullable<System.DateTime> bCreationDate { get; set; }
    }
}
