//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SearchOverAll_Showroom
    {
        public string CNIC { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneNumber2 { get; set; }
        public string CreditRating { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string GCNIC { get; set; }
        public string GName { get; set; }
        public string GFatherName { get; set; }
        public string GAddress { get; set; }
        public string GPhoneNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> GCreationDate { get; set; }
        public int TransactionId { get; set; }
        public int VehicleID { get; set; }
        public string BuyerCNIC { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TRemarks { get; set; }
        public string GuarantorCNIC { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public int Id { get; set; }
        public string EngineNumber { get; set; }
        public string ChasisNumber { get; set; }
        public string Model { get; set; }
        public string CC { get; set; }
        public string VRemarks { get; set; }
        public Nullable<System.DateTime> VCreationDate { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<bool> IsOld { get; set; }
    }
}
