//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string EngineNumber { get; set; }
        public string ChasisNumber { get; set; }
        public string Model { get; set; }
        public string CC { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<bool> IsOld { get; set; }
    }
}
