//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guarantor
    {
        public string CNIC { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
