//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintInstallment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<decimal> InstallmentAmountPayable { get; set; }
        public Nullable<decimal> InstallmentAmountPayed { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalAmountPayedTill { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> TotalAmountPayedbyInstallment { get; set; }
        public Nullable<decimal> TotalRemainingAmount { get; set; }
        public Nullable<System.DateTime> NextInstallmentDueDate { get; set; }
        public string Comments { get; set; }
        public Nullable<int> InstallmentNumber { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCNIC { get; set; }
        public string EnginerNumber { get; set; }
        public string ChasisNumber { get; set; }
    }
}
