//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShowRoomManagementEntities : DbContext
    {
        public ShowRoomManagementEntities()
            : base("name=ShowRoomManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Buyer> Buyers { get; set; }
        public DbSet<Guarantor> Guarantors { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<Installment> Installments { get; set; }
        public DbSet<TempInstallment> TempInstallments { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<PrintInstallment> PrintInstallments { get; set; }
        public DbSet<v_SearchOverAll_Showroom> v_SearchOverAll_Showroom { get; set; }
        public DbSet<v_InstallmentDetail> v_InstallmentDetail { get; set; }
        public DbSet<BlackListedUser> BlackListedUsers { get; set; }
    }
}
