//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempInstallment
    {
        public int InstallmentID { get; set; }
        public int InstallmentNumber { get; set; }
        public decimal InstallmentAmount { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> DueDateStart { get; set; }
        public Nullable<System.DateTime> DueDateEnd { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PayedAmount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> TransactionID { get; set; }
    }
}
