//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoomManagementCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public string BuyerCNIC { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Remarks { get; set; }
        public string GuarantorCNIC { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
    }
}
